### ISSUE TITLE
If data.table has to be used, package maditr might help.

### ISSUE THREAD

**Issue by hope-data-science** [tidyverse/dtplyr#104]
dplyr is good at its syntax, recently I have learned the package maditr that use the least packages to give data.table a dplyr logic. If data.table has to be used to increase the performance, maybe adding as.data.table() and as_tibble() in every "dt_" prefix function in maditr could help build most of dtplyr's functions. For your reference:[https://github.com/gdemin/maditr];[https://cran.r-project.org/web/packages/maditr/index.html].

**Comment by hadley** [comment]
The point of dtplyr is to translate dplyr code directly to high performance data.table code; I don't think maditr would help here.
