### ISSUE TITLE
make `lazy_dt` a S3 method

### ISSUE THREAD

**Issue by xiaodaigh** [tidyverse/dtplyr#105]
I want to support `dtplyr` in my [disk.frame package](https://github.com/xiaodaigh/disk.frame). 

`{disk.frame}` uses dplyr verbs and apply them to files on disk as if they are data.frames. So I want to support a `lazy_dt.disk.frame` method.

Would I be possible? Thanks. Happy to do PR

**Comment by hadley** [comment]
I don't think it makes sense for a constructor to be a generic. Reading the linked issue, I think you'll need to adopt a different strategy in your package now that dplyr is lazy, and hence requires an explicit `collect()` step at the end.
