### ISSUE TITLE
Scoped variants don't work

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#109]
``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

dt <- lazy_dt(data.frame(x = "a", y = 1))

dt %>% mutate_at(vars(x), factor)
dt %>% mutate_if(is.character, length)
#> Source: local data table [?? x 2]
#> Call:   copy(`_DT1`)[, `:=`()]
#> Error in `[.data.table`(copy(`_DT1`), , `:=`()): In `:=`(col1=val1, col2=val2, ...) form, all arguments must be named.
dt %>% summarise_at(vars(x), length)
dt %>% summarise_if(is.character, length)
#> Source: local data table [?? x 0]
#> Call:   `_DT1`[, 0L]
#> 
#> 
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Fixing the `if` variants will require a new generic in dplyr, `tbl_prototype()` so that backends can expose a prototype for the selection to operate on.

**Comment by MichaelChirico** [comment]
What's the intended outcome here? 

Something like

```
dt[ , lapply(.SD, length), .SDcols = sapply(dt, is.character)]
```

?

We don't really have a way of in-lining this as of now, in general (`.SDcols` accepts `patterns` of regular expressions for selecting columns but this is more general), so a "chained" version won't be possible*. Have filed https://github.com/Rdatatable/data.table/issues/3950 to simplify.

* well, possible, but ugly:

```
DT[ , {idx <<- sapply(.SD, is.character); .SD}
    ][ , lapply(.SD, length), .SDcols = idx]; rm(idx)
# even more obscure (not tested)
DT[ , {idx <- sapply(.SD, is.character); f <<- function() {idx = idx; rm(idx, f, envir = .GlobalEnv); idx}
    ][ , lapply(.SD, length), .SDcols = f()]
```
```

**Comment by hadley** [comment]
@MichaelChirico well the scoped variants aren't generic yet, so dtplyr will do the inlining itself (probably not as efficient as having data.table do it, but at least it works)

**Comment by hadley** [comment]
Superseded by #154
