### ISSUE TITLE
Optimize if_else/coalesce to fifelse/fcoalesce?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dtplyr#112]
`data.table` now has its own implementation of `if_else` (`fifelse`) and `coalesce` (`fcoalesce`).

I just tried the following: add two lines to `dplyr/tests/testthat.R`:

```
library(testthat)
library(dplyr)
if_else = data.table::fifelse
coalesce = data.table::fcoalesce

test_check("dplyr")
```

then run `testthat::test_dir('tests')`.

7 tests failed, but the same tests failed if I removed those two lines, so I'm taking that to mean `fifelse` and `fcoalesce` pass usage tests `dplyr` for behavior users expect of those functions.

Does it make sense/would it be straightforward to optimize those functions when used in `dtplyr`?

**Comment by hadley** [comment]
Yeah, I think that makes sense — it's just a matter of adding a few more lines to https://github.com/tidyverse/dtplyr/blob/master/R/tidyeval.R#L61-L75

**Comment by hadley** [comment]
@MichaelChirico I'm likely to be working on this in the next week if you want to take a stab at it. (If you don't have time, don't worry, as I can also do it myself)

**Comment by MichaelChirico** [comment]
yes it's still on my to-do :)

**Comment by MichaelChirico** [comment]
Heads up that we've also got `fcase` in the pipeline, though we opted for a `when-value` pair API as an initial pass, so it won't be a simple drop-in to the formula interface of `case_when`:

https://github.com/Rdatatable/data.table/pull/4021/
