### ISSUE TITLE
group_by and nesting for data.tables

### ISSUE THREAD

**Issue by benjaminleroy** [tidyverse/dtplyr#116]
I noticed that a data.table object doesn't obtain the same result as a tibble or data.frame when using `group_by` and `nest`:

```r
df_tib <- tribble(
  ~g, ~x, ~y,
   1,  1,  2,
   2,  4,  6,
   2,  5,  7,
   3, 10,  NA
)
df_tib %>% group_by(g) %>%
  nest()
```

Outputs:
```
# A tibble: 3 x 2
# Groups:   g [3]
      g           data
  <dbl> <list<df[,2]>>
1     1        [1 × 2]
2     2        [2 × 2]
3     3        [1 × 2]
```

as does 
```r
df <- data.frame(df_tib)
df %>% group_by(g) %>%
  nest()
```

But, 
```r
df_dt <- data.table(df_tib)

df_dt %>% group_by(g) %>%
  nest()
```
returns:
```
                                  data
1 1, 2, 2, 3, 1, 4, 5, 10, 2, 6, 7, NA
Warning message:
`...` must not be empty for ungrouped data frames.
Did you want `data = everything()`? 
```

I believe the group_by structure is not preserved relative to the data.table object. Is that intended/ could it be fixed?

Thanks

**Comment by TysonStanley** [comment]
Not sure if it is of any help for this feature request but I'm working on a blog post about `tidyfast` and how it works with `dtplyr` to nest data tables (it works like `group_nest()`).

**Comment by hadley** [comment]
Part of #168
