### ISSUE TITLE
Re-export pipe?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dtplyr#117]
Should `%>%` be re-exported here? I know `dplyr` & few other packages are doing so.

Was just playing around a bit with only `dtplyr` loaded and surprised to get the `could not find function %>%`

**Comment by hadley** [comment]
I don't _think_ so because I think you'd usually have to have dplyr loaded for dtplyr to be much use

**Comment by MichaelChirico** [comment]
agreed, closing
