### ISSUE TITLE
Translate `map()` calls to `lapply()`?

### ISSUE THREAD

**Issue by TysonStanley** [tidyverse/dtplyr#126]
Since `data.table` evaluates `lapply()` in a special way (see [here](https://jangorecki.gitlab.io/data.cube/library/data.table/html/datatable-optimize.html)), would it be worth translating any `map()` calls prior to the `data.table` evaluation? Or would it be best for users to be told that `lapply()` has additional optimizations in `data.table`?

**Comment by hadley** [comment]
To use this optimisation, you'd need to know about `.SD`, which the average dplyr user won't; and if you know about `.DT`, I suspect you also know about using it with `lapply()`, so on the whole, I don't think this translation would be that useful.
