### ISSUE TITLE
colnames doesn't work on lazy_dt

### ISSUE THREAD

**Issue by AdrienMtgn** [tidyverse/dtplyr#131]
Colnames dosn't seem to work on a lazy_dt but it works on a data.table.
See screenshot below.

![image](https://user-images.githubusercontent.com/29199604/69883930-86ace300-12d6-11ea-9d3b-fd24230b184c.png)

![image](https://user-images.githubusercontent.com/29199604/69884000-c673ca80-12d6-11ea-8046-10390eefb2c0.png)

Am I doing something wrong ?

**Comment by AdrienMtgn** [comment]
It seems like adding a dimnames method for dtplyr_step is enough to do the trick.


```
#' @export 
dimnames.dtplyr_step <- function(x){ 
  list(NULL,x$vars) 
}
```

**Comment by hadley** [comment]
That wouldn't be a good idea, because then you'd expect `$` to also work. If you want to get the names of the variables in the object, try `dplyr::tbl_vars()`
