### ISSUE TITLE
Amenability to "DT-only" / "experimental" features?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dtplyr#133]
I can't say I know the full offering of `dplyr`/`tidyverse` well enough so please correct me if I'm wrong but I believe there are a few features available from `data.table` that haven't yet made it to `dpylr`, e.g.:

 - rolling joins, available in `[`'s `roll` argument
 - non-equi joins, available in `[`'s `on` argument
 - interval joins, available in `foverlaps()`
 - Data roll-up/cube/grouping sets, available in `rollup`/`cube`/`groupingsets`

There are probably more but those come to mind first.

Implementing this in `dtplyr`, since it uses `data.table`'s backend, could allow you to experiment with the frontend API while the "tidyverse-native" backend is forthcoming.

**Comment by jangorecki** [comment]
rollup/cube/groupingsets could be re-used in `dbplyr` straight away. data.table implementation of those was made strictly based on the SQL standard.

**Comment by hadley** [comment]
Yeah, that's definitely possible!

**Comment by johnmackintosh** [comment]
+1

**Comment by hadley** [comment]
Closing this issue because it's not specific enough to be actionable, but definitely in favour of the idea.
