### ISSUE TITLE
Left join columns order changed

### ISSUE THREAD

**Issue by engineerchange** [tidyverse/dtplyr#139]
Thank you for all the work put into dtplyr; it already is saving me loads of time in my day to day. 

It appears that left_join causes columns to change order. Doesn't appear to be an issue with right_join or merge.

``` r
library(data.table)
library(dtplyr)
library(dplyr,warn.conflicts=FALSE)

packageVersion("data.table")
#> [1] '1.12.8'
packageVersion("dtplyr")
#> [1] '1.0.0.9000'

x1 <- data.frame(x = 1:3, y = 1)
x2 <- data.frame(x = 1:3, z = 2)

x1 %>%
  left_join(x2, by="x")
#>   x y z
#> 1 1 1 2
#> 2 2 1 2
#> 3 3 1 2

x1 %>%
  lazy_dt() %>%
  left_join(x2, by="x") %>%
  as_tibble()
#> # A tibble: 3 x 3
#>       x     z     y
#>   <int> <dbl> <dbl>
#> 1     1     2     1
#> 2     2     2     1
#> 3     3     2     1
```

<sup>Created on 2019-12-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Somewhat more minimal reprex:

``` r
library(dtplyr)
library(dplyr, warn.conflicts=FALSE)

x1 <- data.frame(x = 1:3, y = 1)
x2 <- data.frame(x = 1:3, z = 2)

x1 %>%
  left_join(x2, by="x") %>% 
  names()
#> [1] "x" "y" "z"

x1 %>%
  lazy_dt() %>%
  left_join(x2, by="x") %>%
  collect() %>% 
  names()
#> [1] "x" "z" "y"
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Hmmm, this is because of the way that data.table does joins, where the column names are the by vars, the y vars, then the x vars. Reordering the variables after the join would make the translation quite a bit more complicated, and I'm not sure if it's worth it.

**Comment by hadley** [comment]
I could just make this always return a `merge()` instead of trying to use the compact `dt1[dt2]` syntax. @MichaelChirico is this likely to have an performance implications?

**Comment by MichaelChirico** [comment]
merge.data.table always wraps [ IIRC.

the main advantage of [ is the other things available, like merge+assign /
merge+aggregate, non-equi-joins

**Comment by hadley** [comment]
None of which have obvious dplyr translations, so I think it's probably fine to always use `merge()` in the interest of hewing closer to dplyr behaviour.

**Comment by MichaelChirico** [comment]
I agree it makes sense.

fwiw I think the issue could also be fixed with a call to setcolorderv(), if an approach with [ were to be revisited

**Comment by hadley** [comment]
Hmmm, that might be easier — I think I have the needed info to only do that in `collect()`, if there's a mismatch between dplyr and data.table orderings.
