### ISSUE TITLE
Append a "select all" `DT[]` to translation if the last verb is `mutate`

### ISSUE THREAD

**Issue by pnacht** [tidyverse/dtplyr#146]
data.table's `:=` syntax has a side-effect of messing with printing (see [Bug Fixes in data.table 1.9.6](https://github.com/Rdatatable/data.table/blob/master/NEWS.0.md#bug-fixes-1)):

``` r
suppressPackageStartupMessages(library(data.table))

z <- data.table(a = 1)[, b := 1]
z
z
#>    a b
#> 1: 1 1
```

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note how the first time we ask to print `z`, nothing happens. Only after the second print does anything happen.

The solution is to add a final `[]` to the query:

``` r
suppressPackageStartupMessages(library(data.table))

z <- data.table(a = 1)[, b := 1][]
z
#>    a b
#> 1: 1 1
```

This behavior is also present in `dtplyr` whenever a `mutate` is the last verb:

``` r
suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
  library(dtplyr)
})

z <- data.table(a = 1) %>%
  lazy_dt() %>%
  mutate(b = 1) %>%
  as.data.table()
z
z
#>    a b
#> 1: 1 1
```

An obvious workaround is to add a `select(everything())` after the mutate.

While this is arguably best resolved from the `data.table` side, it isn't consistent with `dplyr`, where such a query should print from the get-go. In order to facilitate potential migration from `dplyr` to `dtplyr`, it'd be nice to solve this here.

I'm assuming the performance impact of `DT[]` is negligible, so a trivial solution would be to append a `[]` at the end of all translations, though a more elegant solution (if plausible?) would only do so when the last verb is a `mutate`.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

dt <- lazy_dt(data.frame(x = 1))
dt %>% mutate(b = 1) 
#> Source: local data table [?? x 2]
#> Call:   copy(`_DT1`)[, `:=`(b = 1)]
#> 
#>       x     b
#>   <dbl> <dbl>
#> 1     1     1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
dt %>% mutate(b = 1) %>% data.table::as.data.table()
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Seems reasonable to just do this as part of `as.data.table()`
