### ISSUE TITLE
Summarise does not throw an error for summary values greater than length 1

### ISSUE THREAD

**Issue by tylerferguson** [tidyverse/dtplyr#149]
`summarise `unexpectedly allows summary values of length greater than 1. This can be troublesome if the error is behaviour relied upon for sanity checking values set in `summarise`. Furthermore, I think most people would reasonably assume that the grouping variables can function as unique identifiers after a call to `summarise` but this will no longer be the case when using dtplyr.

Reprex below:
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
library(dtplyr)

a <- tibble(A = c(1,2,3), B = c(4,5,6))

# expected behaviour: Error
a %>%
  group_by(A) %>%
  summarise(C = c(1,2))
#> Error: Column `C` must be length 1 (a summary value), not 2

# unexpected behaviour: continues silently
a %>%
  lazy_dt() %>%
  group_by(A) %>%
  summarise(C = c(1,2)) %>%
  as_tibble()
#> # A tibble: 6 x 2
#>       A     C
#>   <dbl> <dbl>
#> 1     1     1
#> 2     1     2
#> 3     2     1
#> 4     2     2
#> 5     3     1
#> 6     3     2
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is a deliberate change in the development version of dplyr. I think this is a reasonable decision because it enables the use of many more summary functions (e.g. `quantile()`).

**Comment by tylerferguson** [comment]
Thanks for the quick response.

I have seen that this is in the pipeline for dplyr. Any idea when that's due to be released?
Until then this is going to be confusing behaviour for dtplyr.
