### ISSUE TITLE
lazy_dt() breaks the effect of ".drop = FALSE" in group_by(), count(), etc.

### ISSUE THREAD

**Issue by RudolfCardinal** [tidyverse/dtplyr#150]
First -- fantastic packages, as always; thank you.

Using:

- dplyr_0.8.3
- dtplyr_1.0.1 = current as of 2020-02-16
- data.table_1.12.8

the following inconsistent behaviour is observed with respect to the `.drop = FALSE` option to functions like `count()`, `group_by()`:

    library(data.table)
    library(dtplyr)
    library(dplyr)

    # From ?group_by, last example, using count():
    
    tbl <- tibble(
        x = 1:10,
        y = factor(rep(c("a", "c"), each  = 5), levels = c("a", "b", "c"))
    )
    tbl %>% count(y)  # correct, without level "b"
    tbl %>% count(y, .drop = FALSE)  # correct, with level "b"

    # Another example:

    y <- tibble(
        f = factor(rep(1:3, times = 2), levels=1:4)
    )
    y %>% count(f)  # correct, without level 4
    y %>% count(f, .drop = FALSE)  # correct, with level 4

    # But if we start with a data table and use lazy_dt(), we get different behaviour:

    dy <- data.table(
        f = factor(rep(1:3, times = 2), levels=1:4)
    )
    dy %>% lazy_dt() %>% count(f)  # correct, without level 4
    dy %>% lazy_dt() %>% count(f, .drop = FALSE)  # WRONG, without level 4

... i.e. the `lazy_dt()` stage breaks this. It works fine with `as.data.table()` or `as_tibble()` instead, e.g.:

    dy %>% as.data.table() %>% count(f, .drop = FALSE)  # correct, with level 4
    dy %>% as_tibble() %>% count(f, .drop = FALSE)  # correct, with level 4

**Comment by hadley** [comment]
Unfortunately I don't think it's going to be possible to support this in dtplyr because there's no native support in data.table: https://stackoverflow.com/questions/18866796/empty-factors-in-by-data-table. But we can at least make this give a clear error message.

**Comment by hadley** [comment]
Hmmm, the `.drop` argument is specifically provided from the `count.data.frame()` method, not the generic, so given that it's relatively rarely and you now get an obviously wrong result, I think I'll leave this as is.

``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

tbl <- lazy_dt(tibble(
  x = 1:10,
  y = factor(rep(c("a", "c"), each  = 5), levels = c("a", "b", "c"))
))
tbl %>% count(y)
#> Source: local data table [?? x 2]
#> Call:   `_DT1`[, .(n = .N), keyby = .(y)]
#> 
#>   y         n
#>   <fct> <int>
#> 1 a         5
#> 2 c         5
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
tbl %>% count(y, .drop = FALSE)
#> Source: local data table [?? x 3]
#> Call:   copy(`_DT1`)[, `:=`(.drop = FALSE)][, .(n = .N), keyby = .(y, 
#>     .drop)]
#> 
#>   y     .drop     n
#>   <fct> <lgl> <int>
#> 1 a     FALSE     5
#> 2 c     FALSE     5
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
