### ISSUE TITLE
is a dtplyr %>% chain in-place

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/dtplyr#152]
One zippy advantage of a data.table is that transformations can be in-place.

If one writes dplyr %>% chain using dtplyr, will the intermediate steps perform deep copies (dplyr-style) of the table being piped thru or will the output be an in-place transformed version of the input?

**Comment by batpigandme** [comment]
See the copies section of the vignette here:
https://dtplyr.tidyverse.org/articles/translation.html#copies
