### ISSUE TITLE
issue at reshaping data (wide to long)

### ISSUE THREAD

**Issue by tingjhenjiang** [tidyverse/dtplyr#158]
When I transform a data.frame from wide data to long data after I make it supported by dtplyr by adopting dtplyr::lazy_dt(), the result of reshaped dataframe is in error: column names disappeared and targeting columns are not melted.

It seems that dtplyr would call reshape::melt, where everytime I executes the reshaping function, the messages below would appear and indicates that data.table no longer supports reshape2:

> Warning message:
> In data.table::melt(term_to_survey, id.vars = "term", measure.vars = c("SURVEY1",  :
>   The melt generic in data.table has been passed a dtplyr_step_first and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(term_to_survey). In the next version, this warning will become an error.

Meanwhile, calling data.table::melt after dtplyr::lazy_dt() would also be redirected to reshape2::melt, in which errors occur.
＝＝＝＝＝＝＝＝＝＝＝＝＝＝
reproducible example:

```r
term_to_survey <- data.frame("term"=c(5,6,7,7,8,8,9),
                             "SURVEY1"=c("2004citizen","2004citizen","2010env","2010overall","2010env","2010overall","2016citizen"),
                             "SURVEY2"=c("test1","test2","test3","test4","test5","test6","test7")
                             )
term_to_survey %<>% dtplyr::lazy_dt()
data.table::melt(term_to_survey, id.vars="term", measure.vars=c("SURVEY1","SURVEY2"), variable.name = "variablename_of_SURVEY", value.name="SURVEY")
  SURVEY          NA    NA
1      5 2004citizen test1
2      6 2004citizen test2
3      7     2010env test3
4      7 2010overall test4
5      8     2010env test5
6      8 2010overall test6
7      9 2016citizen test7
reshape2::melt(term_to_survey, id.vars="term", measure.vars=c("SURVEY1","SURVEY2"), variable.name = "variablename_of_SURVEY", value.name="SURVEY")
  SURVEY          NA    NA
1      5 2004citizen test1
2      6 2004citizen test2
3      7     2010env test3
4      7 2010overall test4
5      8     2010env test5
6      8 2010overall test6
7      9 2016citizen test7
```
It would be fine if I did not call dtplyr::lazy_dt().

**Comment by hadley** [comment]
You'll currently need to convert back to regular a data table in order to use `melt()`.
