### ISSUE TITLE
Re-licensing dtplyr

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#165]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/tidyverse/dtplyr/graphs/contributors). @alyst, @arunsrinivasan, @christophsax, @hannesmuehleisen, @leondutoit, @lindbrook, @MichaelChirico, @pimentel, @psanker, would you permit us to re-license dtplyr with the MIT license? If so, please comment "I agree" below.

* [x] [@alyst](https://github.com/tidyverse/dtplyr/commits?author=alyst)  
* [x] [@arunsrinivasan](https://github.com/tidyverse/dtplyr/commits?author=arunsrinivasan)  
* [x] [@christophsax](https://github.com/tidyverse/dtplyr/commits?author=christophsax)  
* [x] [@hannesmuehleisen](https://github.com/tidyverse/dtplyr/commits?author=hannesmuehleisen)  
* [x] [@leondutoit](https://github.com/tidyverse/dtplyr/commits?author=leondutoit)  
* [x] [@lindbrook](https://github.com/tidyverse/dtplyr/commits?author=lindbrook)  
* [x] [@MichaelChirico](https://github.com/tidyverse/dtplyr/commits?author=MichaelChirico)  
* [ ] [@pimentel](https://github.com/tidyverse/dtplyr/commits?author=pimentel)  
* [x] [@psanker](https://github.com/tidyverse/dtplyr/commits?author=psanker)

**Comment by alyst** [comment]
I agree, thank you!

**Comment by MichaelChirico** [comment]
go ahead, please & thank you!

**Comment by psanker** [comment]
I agree, thanks!

**Comment by christophsax** [comment]
I agree 👍

**Comment by leondutoit** [comment]
I agree

**Comment by lindbrook** [comment]
I agree.

**Comment by hannesmuehleisen** [comment]
Agree

**Comment by batpigandme** [comment]
Hi @arunsrinivasan and @pimentel,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by arunsrinivasan** [comment]
👍
