### ISSUE TITLE
Add tidyr methods

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#168]
At least to match dbplyr

* [x] `pivot_longer()`
* [x] `pivot_wider()`
* [x] `complete()`
* [x] `expand()`
* [x] `fill()`
* [x] `replace_na()`

**Comment by markfairbanks** [comment]
Closing as the functions listed have all been added to dtplyr

**Comment by hadley** [comment]
🥳 Thanks for all your work on this!
