### ISSUE TITLE
fill.dtplyr_step() design discussion

### ISSUE THREAD

**Issue by markfairbanks** [tidyverse/dtplyr#196]
@hadley Wanted to get your thoughts on a `fill()` translation before I made a pull request. The issue comes up because `data.table::nafill()` [currently only works for integer and double columns](https://github.com/Rdatatable/data.table/issues/3992).

There are workarounds in that issue to get it to work with other types, but even the fastest one is pretty slow (using a comparison to `vctrs::vec_fill_missing()`):
``` r
library(vctrs)
library(data.table)

workaround <- function(x) {
  x[data.table::nafill(replace(seq_along(x), is.na(x), NA_integer_), "locf")]
}

data_size <- 1000000
chr_vec <- sample(c(letters[1:10], NA), data_size, TRUE)
int_vec <- sample(c(1:10, NA), data_size, TRUE)

bench::mark(
  data.table_int = data.table::nafill(int_vec),
  vctrs_int = vctrs::vec_fill_missing(int_vec),
  workaround_chr = workaround(chr_vec),
  vctrs_chr = vctrs::vec_fill_missing(chr_vec),
  check = FALSE
)
#> # A tibble: 4 x 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 data.table_int 317.11µs  582.2µs    1260.     3.85MB     237.
#> 2 vctrs_int        2.38ms   2.63ms     345.    11.45MB     213.
#> 3 workaround_chr  13.45ms  14.09ms      66.4   23.25MB     126.
#> 4 vctrs_chr         3.6ms   4.13ms     223.    15.26MB     193.
```

In {tidytable} I got around this issue by using an internal function that uses `data.table::nafill()` if the vector is an integer or double vector, and using `vctrs::vec_fill_missing()` for all other types. I built out how this would look in {dtplyr} [here](https://github.com/markfairbanks/dtplyr/blob/fill/R/fill.R), but wasn't sure if it's the direction you would want to take it. Note I called the internal function `nafill()`, as that would present to the user a data.table-like translation, but give them the functionality of `tidyr::fill()`.

How it would look to the user:

``` r
library(dtplyr)
library(tidyr)
library(dplyr)

test_df <- lazy_dt(tibble(x = c("a", NA, "c")))

test_df %>%
  fill(x)
#> Source: local data table [3 x 1]
#> Call:   copy(`_DT1`)[, `:=`(x = nafill(x, "locf"))]
#> 
#>   x    
#>   <chr>
#> 1 a    
#> 2 a    
#> 3 c    
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

The advantage is that it looks like data.table code. The disadvantage is if they copied and pasted that code it wouldn't work for non-numeric columns.

So I guess the overall question is which approach would you prefer?
* `fill()` simply uses `data.table::nafill()` and fails in the case of non-numeric columns
* `fill()` uses `data.table::nafill()` for numeric columns and uses the slow workaround for non-numeric columns.
* `fill()` uses a combination of `data.table::nafill()` and `vctrs::vec_fill_missing()`
  - And for this case would you want to call the internal function something other than `nafill()`

**Comment by hadley** [comment]
For now, I think I'd prefer option 1 — just fail (in the data.table call) on non-numeric columns. We can document that, and then update the docs once data.table expands support.

**Comment by markfairbanks** [comment]
Sounds good 👍
