### ISSUE TITLE
Issues using apply function

### ISSUE THREAD

**Issue by jdmoralva** [tidyverse/dtplyr#226]
Sorry if this issue looks irrelevant, 

I'm trying to replicate the use of an anonymous function with dplyr verbs, but I can't achieve the desired result. Maybe It's because the use of a lapply function in data.table is quite different.

Any suggestion? 

```r
library(data.table)
library(dtplyr)
library(dplyr)

# Using dtplyr
set.seed(2021)

df <- data.frame(
  x = sample(c(0,1), 100, replace = TRUE),
  y = sample(seq(1,50,1), 100, replace = TRUE),
  z = sample(seq(1,100,1), 100, replace = TRUE)
)

dt <- as.data.table(df)

# dt[, `:=`(total = apply(.SD, 1, FUN = function(x) sum(x)), 
#           max = apply(.SD, 1, FUN = function(x) max(x))), 
#    .SDcols = 2:3]

lazy_dt(dt, immutable = FALSE) %>% 
  mutate(
    total = apply(.[2:3], 1, FUN = function(x) sum(x)),
    max = apply(.[2:3], 1, FUN = function(x) max(x))
  ) %>% 
  as.data.table()

# Error in `[.data.table`(`_DT22`, , `:=`(total = apply(.SD[2:3], 1, FUN = function(x) sum(x)),  : 
# Supplied 2 items to be assigned to 100 items of column 'total'. If you wish to 'recycle' the RHS please use rep() to make this 
# intent clear to readers of your code.

```

PD. sum and max functions used for explanatory purposes

**Comment by myoung3** [comment]
In dplyr, I assume `.[2:3]` refers to columns?  Because in the translated data.table syntax it's referring to rows of .SD. 

That's because `i` in `dt[i]`, unlike lists, refers to rows.  This might be a tricky one to solve.

**Comment by myoung3** [comment]
This explains the root of the issue:
```
library(data.table)
x <- data.frame(v1=1:3,v2=2:4)
x[1:2]
setDT(x)
x[1:2]
```
by design, x[i] subsets rows in data.table (unlike for data.frames)

**Comment by hadley** [comment]
Isn't this a use case for `across()`?

**Comment by jdmoralva** [comment]
> 
> 
> Isn't this a use case for `across()`?

Thanks for answering. I think not, because the goal is not to operate on the columns, but to create new columns. 
This statement finally worked: 

```r
lazy_dt(dt, immutable = FALSE) %>% 
  mutate(
    total = apply(., 1, FUN = function(x) sum(x[2:3])),
    max = apply(., 1, FUN = function(x) max(x[2:3]))
  )
```

Is there another way to work with the apply family functions for column mutate?

**Comment by myoung3** [comment]
Not quite. It's more like a `rowwise` operation.
```r
library(dplyr)

# Using dtplyr
set.seed(2021)

df <- data.frame(
  x = sample(c(0,1), 100, replace = TRUE),
  y = sample(seq(1,50,1), 100, replace = TRUE),
  z = sample(seq(1,100,1), 100, replace = TRUE)
)



df %>% 
  summarize(
    total = apply(.[2:3], 1, FUN = function(x) sum(x)),
    max = apply(.[2:3], 1, FUN = function(x) max(x))
  ) 

#not the same
df %>%
  summarize(across(2:3, sum))

#also not the same, but closer. 
 #but this won't work either since across evaluates FUN on each each column separately this just gives the columns back unaltered:
df %>%
  summarize(across(2:3, `+`))


#it's something like this
df %>% 
  rowwise() %>% 
  summarise(total=sum(c(y, z)),max=max(c(y,z)))

```

I'm not sure the best way to do this in dplyr (my solution is suboptimal since it requires retyping `c(y,z)`). 

In any case it should probably work in `dtplyr` since it works in `dplyr`--even if using `apply(.,1,fun)` in a mutate/summarize statement isn't best practice.

**Comment by myoung3** [comment]
@jdmoralva Also keep in mind the optimal approach for rowwise operations is always to use vectorized functions:

```
df %>% 
  summarise(total=y+z,max=pmax(y,z))
```
(you probably know this and are just using sum and max as standins for functions which aren't vectorized).
(also `+` is more limited that pmax since it doesn't have na.rm. there really should be a psum in base R)

**Comment by myoung3** [comment]
This is probably the clearest dplyr solution (assuming the functions aren't vectorized):
```r
df %>% 
  select(2:3) %>%
  rowwise() %>%
  mutate(total=sum(y, z),max=max(y,z))
```

**Comment by hadley** [comment]
Oh `rowwise()` + `c_across()`:

```R
df %>% 
  rowwise() %>% 
  summarise(total= sum(c_across()), max=max(c_across()))
```

Regardless, this doesn't seem like a dtplyr problem, so I'm going to close.
