### ISSUE TITLE
Error in env_get_list(ns_env("data.table"), dt_funs) :    argument "default" is missing, with no default

### ISSUE THREAD

**Issue by sanjmeh** [tidyverse/dtplyr#235]
My working shiny code breaks after including `dtplyr` in the library.
I quickly removed `dtplyr` from the loaded shiny packages so the code started working on the shiny server but continues to fail (with following error) when I run it locally (perhaps the package is in memory still).

```
Error in env_get_list(ns_env("data.table"), dt_funs) : 
  argument "default" is missing, with no default
```

My shiny code calls a function `dygen` with a data.table as its first argument. The function resides in `global.R`. Reproducing the section where the error pops in.

```r
# reprex
dygen <- function(dt){
    browser()
    if(isTruthy(dt) && nrow(dt) >0 ){
        dt %>% ... # rest of my code
}
}

```

I am not initialising R as I want this problem to be resolved for others too. If there are few things you want me to try I will keep it ready.

Update:
Inside the debugger if I try to see the structure of dt it returns a horrendous nested list of 9. I have no idea how my data.table got converted to this complicated list.

```
> str(dt)

```
> List of 9
>  $ parent       :List of 11
>   ..$ parent       :List of 10
>   .. ..$ parent       :List of 10
>   .. .. ..$ parent       :List of 11
>   .. .. .. ..$ parent       :List of 8
>   .. .. .. .. ..$ parent       :Classes ‘data.table’ and 'data.frame':	525146 obs. of  6 variables:
>   .. .. .. .. .. ..$ topic: chr [1:525146] "dand/ELM8420" "dand/RUT" "dand/RUT" "dand/RUT" ...
>   .. .. .. .. .. ..$ ts   : POSIXct[1:525146], format: "2021-03-24 14:58:18" "2021-03-24 14:58:22" "2021-03-24 14:58:22" "2021-03-24 14:58:22" ...
```

```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by sanjmeh** [comment]
Finally I have an explicit error message implicating the `dtplyr` package. (Note: this problem is beyond a reprex @hadley as it appears the sequence of package loading matters, or, perhaps an interaction with some other environment variable that is beyond my knowledge). I could not replicate it on my mac while the problem is repeatable on the ubuntu server (ubuntu 16.04). It comes every time.

The replication on my ubuntu server is as simple as this reprex.

```
library(dtplyr)
library(data.table)
library(dplyr)

dt<- data.table(x=1:10,y=rnorm(10))

dt %>% filter(y>0)
```
This is the error:
```
Registered S3 method overwritten by 'dtplyr':
  method             from       
  rename.dtplyr_step R_GlobalEnv
Error in env_get_list(ns_env("data.table"), dt_funs) : 
  argument "default" is missing, with no default
```
While this goes through

```
dt %>% as.data.frame %>% filter(y>0)
  x         y
1 1 0.6679814
2 4 1.9855064
3 6 0.2701171
4 7 0.2774657
5 9 1.8570423
```
BTW the detaching of the package dtplyr did not have any impact (it seems R does not cleanly detach).

` detach("package:dtplyr", unload=TRUE)`

Could the above facts give some clues on where the problem could be? 

Pls note: I know that on reinitialising R the problem could possibly go away. But that won't help you catch the bug. So I would like to hang on, till the bug reason is clear.

**Comment by hadley** [comment]
If you can not recreate it in a reprex, then it's extremely unlikely that I will be able to help you.

**Comment by myoung3** [comment]
This could be related to data.table's version number. We've bumped the
dependency requirement of data.table's version in dev dtplyr. What version
of data.table are you using? If it's out of date, try updating it and
checking if the problem goes away.

**Comment by sanjmeh** [comment]
Yess.. the problem went away --- either it was the upgrade of data.table from 1.12 to 1.14, or a mere restarting of R that solved it. If I encounter the problem again (which is unlikely) I will flag my finding here. For now we can close the issue.

**Comment by capitantyler** [comment]
same problem. Restarting R was the visible solution have found

**Comment by helgig1** [comment]
Same problem, restarting R and updating data.table to 14.0 solved the problem.
