### ISSUE TITLE
Travis CI error on GitHub repo

### ISSUE THREAD

**Issue by StatsGary** [tidyverse/dtplyr#256]
This is an easy fix, but the Travis CI is not picking up this repo.

**Comment by hadley** [comment]
We no longer use travis.

**Comment by StatsGary** [comment]
Perhaps take the build button off the Readme page?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by hadley** [comment]
It's not there now, so must've been removed at some point in the past.
