### ISSUE TITLE
summarize(across(where)) fails when using a predicate and acts unexpectedly with predicate negation

### ISSUE THREAD

**Issue by roni-fultheim** [tidyverse/dtplyr#271]
I have been trying to summarize across numeric columns using dtplyr and `summarise(across(where(is.numeric)))` and got the error `can't rename variables in this context`. It took me quite a while to figure out the reason for the error is the usage of a predicate within `summarize` is not possible with dtplyr.
Is there any substitute for using `is.numeric` besides for naming all columns?
Thank you

The following code 1) shows error when using predicate, 2) show how the negation does not fail and applies given function to all variables (numeric and non-numeric)
```r
library(ggplot2)
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

# fails
diamonds %>% lazy_dt() %>% group_by(color) %>% summarise(across(!where(is.numeric), first))

# applies function to all variables
diamonds %>% lazy_dt() %>% group_by(color) %>% summarise(across(!where(is.numeric), first))

# unlike the equivalent statement using a data frame which only returns the relevant variables
diamonds %>% group_by(color) %>% summarise(across(!where(is.numeric), first))
```

**Comment by mgirlich** [comment]
Unfortunately, these predicates do not work because the column type is (in general) not known. So, there is no other way than to explicitly name the columns to transform. Maybe other `tidyselect` helpers can help you there, for example something like

```r
diamonds %>% 
  group_by(color) %>% 
  summarise(across(c(carat, depth:z), mean))

iris %>% 
  group_by(Species) %>% 
  summarise(across(matches("^Sepal|Petal")))
```

The error message is indeed not very helpful. When https://github.com/r-lib/tidyselect/issues/226 is implement a more helpful error message can be implemented.

**Comment by cb12991** [comment]
I've ran into the same issue as well. It took me a while to discover why `across(where(is.character)` was not working with a `lazy_dt`. It's not the end of the world as you can use other `tidyselect` helpers mentioned above; just wondering if this was something that will be fixed in the future?
