### ISSUE TITLE
dtplyr changes results of nrow() and colnames() functions

### ISSUE THREAD

**Issue by lutzgruber-quantco** [tidyverse/dtplyr#283]
Hi,

At various places throughout my code I track the number of rows of a table, and some of my functions verify if the input table contains the required variables. I do this usually using the `nrow` and `colnames` functions. When dtplyr is loaded, `nrow` returns `NA` and `colnames` returns `NULL`, which breaks existing code.

```
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



> data.table::data.table(x = 1:5) %>% mutate(y = 2:6) %>% nrow()
[1] 5
> data.table::data.table(x = 1:5) %>% mutate(y = 2:6) %>% colnames()
[1] "x" "y"


> library(dtplyr)

> data.table::data.table(x = 1:5) %>% mutate(y = 2:6) %>% nrow()
[1] NA
> data.table::data.table(x = 1:5) %>% mutate(y = 2:6) %>% colnames()
NULL
```

Could dtplyr please provide methods for these functions so that useful values are returned?

Thank you.

**Comment by eutwt** [comment]
I don't think there is any way to reliably track the number of rows, because it depends when/where you put the final `as.data.table`. (Unless you already collected the results by converting to a data frame, in which case `nrow` would already work anyway)

``` r
library(dplyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)
library(dtplyr, warn.conflicts = FALSE)

dt <- 
  as.data.table(mtcars) %>% 
    summarise(data.frame(z = rep(1, n)))

dtp_nrow <- function(.data) nrow(as.data.table(.data))
n <- 10
dtp_nrow(dt)
#> [1] 10
n <- 20
dtp_nrow(dt)
#> [1] 20
```

<sup>Created on 2021-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lutzgruber-quantco** [comment]
I think your implementation of `dtp_nrow` is what I would want `nrow` to do; I generally expected these functions return what they would return if the results had already been collected at the time the functions are called. Maybe there could be a more efficient way than retrieving the full result of `as.data.table`--not all columns are needed to evaluate the number of rows, for example. Otherwise, this is exactly what I think should dtplyr should do by default so that it can be used without breaking existing code.

**Comment by hadley** [comment]
I think it would be very confusing if `nrow()` caused all the computations to be run. Unfortunately, I don't think there's any way for dtplyr to do you what you want here, and you'll need to take a different approach to solving the root problem.
