### ISSUE TITLE
`mutate` inconsistencies with dplyr

### ISSUE THREAD

**Issue by eutwt** [tidyverse/dtplyr#287]
Using this issue to maintain a collection of (mostly minor) differences between dplyr and dtplyr mutate. Maybe it's easier to prioritize between them with them all listed together, if there's a desire to fix them.

Please don't take this as criticism of dtplyr, I love using this package  😄

1. ~~Unusual `across` results when `.fns` is a formula whose RHS is not a call~~
    -  covered by #288 
2. ~~Cannot use anonymous (non-purrr) functions in `across`~~
    -  covered by #288 
3. Cannot use purrr-style formula functions with more than 1 argument
4. #281

5. Cannot remove new columns created in mutate with `[colnm] = NULL`
6. ~~Cannot use `.before` and `.after`~~
    - covered by #291
7. Cannot use `.keep`
8. No splicing of data.frame inputs
9. Cannot treat across output as a data.frame e.g. `df %>% mutate(a = do.call(coalesce, across(starts_with('a'))))`

------
**3. Cannot use purrr-formula functions with more than 1 argument**

``` r
library(dplyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)

dt <- data.table(a = 1:2)

dt %>%
  mutate(across(a, ~ .x + .y, 1)) %>% 
  as_tibble()
#> # A tibble: 2 × 1
#>       a
#>   <dbl>
#> 1     2
#> 2     3

library(dtplyr)

dt %>%
  mutate(across(a, ~ .x + .y, 1)) %>% 
  as_tibble()
#> Error in eval(jsub, SDenv, parent.frame()): object '.y' not found
```

<sup>Created on 2021-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**5. Cannot remove new columns created in mutate with `[colnm] = NULL`**

``` r
library(dplyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)

dt <- data.table(a = 1:2)

dt %>%
  mutate(b = 3, b = NULL) %>% 
  as_tibble()
#> # A tibble: 2 × 1
#>       a
#>   <int>
#> 1     1
#> 2     2

library(dtplyr)

dt %>%
  mutate(b = 3, b = NULL) %>% 
  as_tibble()
#> Error in `[.data.table`(copy(`_DT1`), , `:=`(b = 3, b = NULL)): Can't assign to the same column twice in the same query (duplicates detected).
```

<sup>Created on 2021-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eutwt** [comment]
Most of these have been addressed

**Comment by markfairbanks** [comment]
> 8. No splicing of data.frame inputs

@eutwt I opened a couple issues for the ones that haven't been implemented yet. Can you open a new issue with a reprex for this? I'm not sure what you meant by this one.
