### ISSUE TITLE
Implement `unite()`

### ISSUE THREAD

**Issue by jtlandis** [tidyverse/dtplyr#301]
Hello, great work on the `dtplyr` package, its  a really nice addition to the `tidyverse`. I was wondering if there will be more methods that extend some of `tidyr` generics. This is more or less an extended feature request  to #266.

Most people who've adapted to using `dplyr` have likely relied on a few `tidyr` functions.

I think many people would benefit from the addition of:

* nest.dtplyr_step
* unnest.dtplyr_step
* fill.dtplyr_step
* pivot_longer.dtplyr_step (to pair with the existing `pivot_wider.dtplyr_step`)
* separate.dtplyr_step
* unite.dtplyr_step

There already exists a package out there that attempts to address these functions named `tidyfast`. Only downside is that these functions would force a lazy_dt to execute its steps as I believe the first step in `tidyfast` functions is to coerce the object with `as.data.table()`

**Comment by markfairbanks** [comment]
FYI these exist for all of those functions except `unite()` and `unnest()` in the development version of dtplyr.

```r
devtools::install_github("tidyverse/dtplyr")
```

**Comment by markfairbanks** [comment]
As far as `unnest()` - #266 is already an open request for it. However there isn't one for `unite()` yet, so I changed this feature request to adding that one 👍

**Comment by jtlandis** [comment]
Ahh, I see, the CRAN version is not yet updated to the dev version. Thanks for letting me know!
