### ISSUE TITLE
tidyr::fill(everything()) fails for character columns

### ISSUE THREAD

**Issue by lindeloev** [tidyverse/dtplyr#327]
This fails and I would expect it to fill the NA in the character column:

```r
data.frame(x = c("A", NA, "B")) %>%
    dtplyr::lazy_dt() %>%
    tidyr::fill(everything())
```

> Error in nafill(x, "locf") : 
>   'x' argument must be numeric type, or list/data.table of numeric types

It runs as expected without `everything()` and on numeric data, but the mere presence of a character column causes it to fail.

R 4.1.1
dtplyr 1.2.0 installed from CRAN
tidyr 1.1.4 installed from CRAN

**Comment by markfairbanks** [comment]
Unfortunately this is a limit of `data.table` as it doesn't support filling with character columns yet (see https://github.com/Rdatatable/data.table/issues/3992).

For now we would recommend using `tidyr::fill()` directly on a data frame instead of a `lazy_dt`.

**Comment by markfairbanks** [comment]
In [the documentation](https://dtplyr.tidyverse.org/reference/fill.dtplyr_step.html) you'll see it mentioned that `fill()` only works on numeric columns in `dtplyr`.

There was a design discussion [here](https://github.com/tidyverse/dtplyr/issues/196) around how to handle `fill()` in `dtplyr` if you want some more context.
