### ISSUE TITLE
should emit a warning if data.table is not loaded in the environment?

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/dtplyr#351]
Is it mandatory that the data.table package is loaded in the environment to use dtplyr or is it just enough to have it installed?
Should `lazy_dt()` emit a warning if the data.table package is not loaded?

**Comment by markfairbanks** [comment]
It's not mandatory for `data.table` to be loaded for `dtplyr` to work. It's enough to have it installed. In fact if you install `dtplyr` it will install `data.table` automatically if it's not already installed.

Here's a simple example to show that `dtplyr` works without `data.table` being loaded:

``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1:3, y = c("a", "a", "b"))

df %>%
  lazy_dt() %>%
  group_by(y) %>%
  summarise(mean_x = mean(x)) %>%
  as_tibble()
#> # A tibble: 2 × 2
#>   y     mean_x
#>   <chr>  <dbl>
#> 1 a        1.5
#> 2 b        3
```
