### ISSUE TITLE
dplyr:across does not work with data.table objects

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [tidyverse/dtplyr#355]
Hi,

Looks like `dtplyr` and `dplyr:across` don't get along when the table is a `data.table` instead of a data frame or tibble.

```r
# Works fine with data frame
group <- 'Species'
iris %>% 
    dplyr::group_by(
        dplyr::across(
            dplyr::all_of(group)
        )
    ) %>% 
    dplyr::summarize(n = dplyr::n())

# # A tibble: 3 x 2
#  #  Species        n
#   <fct>      <int>
# 1 setosa        50
# 2 versicolor    50
# 3 virginica     49

# Doesn't work with data.table
group <- 'Species'
iris %>% 
    data.table::as.data.table() %>% 
    dplyr::group_by(
        dplyr::across(
            dplyr::all_of(group)
        )
    ) %>% 
    dplyr::summarize(n = dplyr::n())

#Error: Must subset columns with a valid subscript vector.
#x Subscript has the wrong type `function`.
#It must be logical, numeric, or character.
#Run `rlang::last_error()` to see where the error occurred.
```

Andreas

**Comment by markfairbanks** [comment]
Have you updated to the latest version of `dtplyr`? Everything works fine when I run this.

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

group <- 'Species'
iris %>% 
    data.table::as.data.table() %>% 
    dplyr::group_by(
        dplyr::across(
            dplyr::all_of(group)
        )
    ) %>% 
    dplyr::summarize(n = dplyr::n())
#> Source: local data table [3 x 2]
#> Call:   `_DT1`[, .(n = .N), keyby = .(Species)]
#> 
#>   Species        n
#>   <fct>      <int>
#> 1 setosa        50
#> 2 versicolor    50
#> 3 virginica     50
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

**Comment by groceryheist** [comment]
I just hit this bug right now.

**Comment by markfairbanks** [comment]
@groceryheist do you have an example this occurs on? Or does it occur on the example above?

**Comment by groceryheist** [comment]
It worked fine on the development version

**Comment by andreassoteriadesmoj** [comment]
> Have you updated to the latest version of `dtplyr`? Everything works fine when I run this.
> 
> ```r
> library(data.table)
> library(dtplyr)
> library(dplyr, warn.conflicts = FALSE)
> 
> group <- 'Species'
> iris %>% 
>     data.table::as.data.table() %>% 
>     dplyr::group_by(
>         dplyr::across(
>             dplyr::all_of(group)
>         )
>     ) %>% 
>     dplyr::summarize(n = dplyr::n())
> #> Source: local data table [3 x 2]
> #> Call:   `_DT1`[, .(n = .N), keyby = .(Species)]
> #> 
> #>   Species        n
> #>   <fct>      <int>
> #> 1 setosa        50
> #> 2 versicolor    50
> #> 3 virginica     50
> #> 
> #> # Use as.data.table()/as.data.frame()/as_tibble() to access results
> ```

@markfairbanks- the update did the trick, thanks.
