### ISSUE TITLE
Want to support set_names()

### ISSUE THREAD

**Issue by yqqhanghang** [tidyverse/dtplyr#373]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
```

**Comment by markfairbanks** [comment]
Thanks for the feature request! Currently `dtplyr` only does translations for `dplyr` and `tidyr` functions - `set_names()` comes from `rlang`/`purrr`.

So we aren't planning on adding `set_names()` - but here is a function that will work in `dtplyr`'s workflow that you can use in the meantime:

``` r
library(dplyr, w = FALSE)
library(dtplyr)
library(data.table)

dt_set_names <- function(x, nm = names(x)) {
  .names <- syms(x$vars)
  names(.names) <- nm
  
  x %>%
    rename(!!!.names)
}

df <- lazy_dt(data.table(x = 1:3, y = 1:3))

df %>%
  dt_set_names(c("a", "b"))
#> Source: local data table [3 x 2]
#> Call:   setnames(copy(`_DT1`), c("x", "y"), c("a", "b"))
#> 
#>       a     b
#>   <int> <int>
#> 1     1     1
#> 2     2     2
#> 3     3     3
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

Hope this helps! If you have any questions let me know.
