### ISSUE TITLE
group_by.dtplyr_step issue

### ISSUE THREAD

**Issue by gpierard** [tidyverse/dtplyr#383]
The below example illustrates a potential bug found with group_by.dtplyr_step, please see [this stackoverflow question](https://stackoverflow.com/q/73267732/5224236) for workarounds. 

-------------------------------------------------------------------

I'd like to group_by across several variables in dtplyr within a lapply loop, and I find that I somehow can't use the same syntax as dplyr after calling lazy_dt().

```
library(dplyr)
mycolumns= c("Wind", "Month", "Ozone", "Solar.R")
columnpairs <- as.data.frame(combn(mycolumns, 2))

#         V1    V2      V3    V4      V5      V6
#    1  Wind  Wind    Wind Month   Month   Ozone
#    2 Month Ozone Solar.R Ozone Solar.R Solar.R

result_dplyr <- lapply(columnpairs, function(x) {
  airquality %>% 
    select(all_of(x)) %>% 
    group_by(across(all_of(x))) %>% filter(n() > 1)
  }
)

$V1
# A tibble: 105 x 2
# Groups:   Wind, Month [40]
    Wind Month
   <dbl> <int>
 1   7.4     5
 2   8       5
 3  11.5     5
 4  14.9     5
 5   8.6     5
 6   8.6     5
 7   9.7     5
 8  11.5     5
 9  12       5
10  11.5     5
# ... with 95 more rows
```

Using the same syntax, I encounter an issue after calling lazy_dt with dtplyr.

```
library(dtplyr)
airq <- lazy_dt(airquality)

lapply(columnpairs, function(x) {
  airq %>% select(all_of(x)) %>% 
    group_by(across(all_of(x))) %>% filter(n() > 1)
})

Error in `all_of()`:
! object 'x' not found
```

This was answered with workarounds at https://stackoverflow.com/q/73267732/5224236

**Comment by eutwt** [comment]
Thanks for the bug report! It looks like this is fixed in the development version, since https://github.com/tidyverse/dtplyr/pull/318. I'll close this now, but will reopen if you install using `devtools::install_github("tidyverse/dtplyr")` and still see a problem.

Reprex using v1.12.1 (current CRAN version)

``` r
devtools::load_all('~/Documents/GitHub/dtp')
#> ℹ Loading dtplyr
#> Warning: package 'testthat' was built under R version 4.1.2
library(dplyr, warn.conflicts = FALSE)

fun <- function(df, x) {
  df %>% group_by(across(all_of(x)))
}

lazy_dt(data.frame(a = 1)) %>% 
  fun('a')
#> Error in `dt_squash_across()` at dtp/R/tidyeval.R:88:4:
#> Caused by error in `all_of()`:
#> ! object 'x' not found
```

<sup>Created on 2022-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Reprex using dev dtplyr (cf7c2d8b9ca5586a96fa9ee3e44c9eb56d9d1a33)

``` r
devtools::load_all('~/Documents/GitHub/dtp')
#> ℹ Loading dtplyr
#> Warning: package 'testthat' was built under R version 4.1.2
library(dplyr, warn.conflicts = FALSE)

fun <- function(df, x) {
  df %>% group_by(across(all_of(x)))
}

lazy_dt(data.frame(a = 1)) %>% 
  fun('a')
#> Source: local data table [1 x 1]
#> Groups: a
#> Call:   `_DT1`
#> 
#>       a
#>   <dbl>
#> 1     1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2022-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
