### ISSUE TITLE
dtplyr release?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#388]
I need to do a dtplyr release to fix [dtpl](https://cran.r-project.org/web/checks/check_results_dtplyr.html) — any concerns with me releasing a minor version that includes all the current fixes?

**Comment by markfairbanks** [comment]
Nope - it's at a good point for release IMO.

**Comment by hadley** [comment]
Oh https://github.com/tidyverse/dtplyr/pull/379 adds a dependency on dev tidyselect 😬

**Comment by hadley** [comment]
So might be easier to just do a hot patch based on last CRAN release.

**Comment by eutwt** [comment]
Oops, yeah was assuming we wouldn't release before dplyr based on discussion in #312

**Comment by hadley** [comment]
Oh yeah, definitely best to hot patch then.

**Comment by hadley** [comment]
Closing in favour of #389
