### ISSUE TITLE
`lazy_dt()` and custom dplyr functions.

### ISSUE THREAD

**Issue by NicChr** [tidyverse/dtplyr#402]
Hi, I noticed that when loading the dtplyr library, all data.tables get converted to lazy_dt objects by default when calling a dplyr function, even if `lazy_dt()` isn't called. 
This default behaviour can be problematic when using custom dplyr-based functions.

See the dummy example below which showcases a trivial custom function that returns the number of unique rows.
```r
n_unique_rows <- function(data){
  unique_data <- dplyr::distinct(data)
  nrow(unique_data)
}
library(dplyr)
library(data.table)
iris_dt <- as.data.table(iris)

n_unique_rows(iris)
[1] 149
n_unique_rows(iris_dt)
[1] 149

library(dtplyr)
n_unique_rows(iris)
[1] 149
n_unique_rows(iris_dt)
[1] NA
```
This can of course be remedied by calling `collect()` after the `distinct()` call, but I would argue this strategy may become impractical when additional complexity is introduced.

Apologies if this has been brought up in another issue or is irrelevant, but I was just wondering if this is expected behaviour.

**Comment by markfairbanks** [comment]
If you install the development version of dtplyr using `devtools::install_github("tidyverse/dtplyr")` this has been changed due to the issues it was causing. You now need to explicitly call `lazy_dt()` on a data frame to opt in to `dtplyr` behavior.

``` r
n_unique_rows <- function(data){
  unique_data <- dplyr::distinct(data)
  nrow(unique_data)
}

library(dplyr)
library(data.table)
library(dtplyr)

iris_dt <- as.data.table(iris)

n_unique_rows(iris)
#> [1] 149
n_unique_rows(iris_dt)
#> [1] 149
```
