### ISSUE TITLE
lead / lag within function with .data$

### ISSUE THREAD

**Issue by shriv** [tidyverse/dtplyr#441]
I'm using `dtplyr` within an R package of data transformations.  I'm using `dtplyr_1.3.1` and  `dplyr_1.1.1` on an M1 mac. 

I rely heavily on `lead()` and `lag()`. However, I find that neither `lead()` nor `lag()` can be used with columns referenced with `.data$<column_name>`. `test_fn_working()` has no issues but if you run `test_fun_not_working()` from the reprex, you get the following error. 

Is there a workaround to use `.data$<column_name>` within `lead()` and `lag()` functions? 

```
Error:
! Can't subset `.data` outside of a data mask context.
Run `rlang::last_trace()` to see where the error occurred.
```

```r
library(dplyr)
library(dtplyr)

test_fn_working <- function(){
  
  dplyr::tibble(
    a = seq(1, 10, 1)
  ) |> 
    dtplyr::lazy_dt() |> 
    dplyr::mutate(
      b = lead(a)
    )
}

test_fn_not_working <- function(){
  
  dplyr::tibble(
    a = seq(1, 10, 1)
  ) |> 
    dtplyr::lazy_dt() |> 
    dplyr::mutate(
      b = lead(.data$a)
    )
}
```

**Comment by shriv** [comment]
Hi @markfairbanks and @eutwt - thanks so much for merging the PR for this bug so quickly! :-) Much appreciated..! Do you when you might release a dev version with this fix? Thanks!

**Comment by markfairbanks** [comment]
You're welcome, thanks for letting us know about the issue 😄 

You can install the dev version that contains the fix with this command:

```r
devtools::install_github("tidyverse/dtplyr")
```

As for the next CRAN release, I would guess it will be in a few months.

**Comment by shriv** [comment]
Fab! I'll install the dev version to get the fix :-)
