### ISSUE TITLE
Consequences of data.table group uniqueness

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#79]
Need to think through the consequences of this:

``` r
library(data.table)
data.table(x = c(1, 1, 2))[, length(x)]
#> [1] 3
data.table(x = c(1, 1, 2))[, length(x), by = .(x)]
#>    x V1
#> 1: 1  1
#> 2: 2  1
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by MichaelChirico** [comment]
IINM basically what's happening here is `x` is not part of `.SD` and is "scoped in" from `by`. `by` is included as a `list` like `.BY = list(x = 1)` and then `.BY = list(x = 2)`.

Group size will always be available as `.N`. HTH further if needed.

**Comment by hadley** [comment]
The variables listed in `by` are always removed from `.SD`?

**Comment by MichaelChirico** [comment]
In effect yes.

Actually `.SD` is built up from scratch via `all.vars(substitute(j))` & `.SDcols`; `byvars` (the variables in `.BY`) are excluded from the possible set. Then some complication to allow `get`/`mget` to work...

**Comment by hadley** [comment]
This doesn't seem to have caused problem in practice, so I'm going to close.
