### ISSUE TITLE
could not find function "lazy_dt"

### ISSUE THREAD

**Issue by tomazweiss** [tidyverse/dtplyr#86]
When I try to run the example from https://github.com/tidyverse/dtplyr I get an error:

```r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

mtcars2 <- lazy_dt(mtcars)

Error in lazy_dt(mtcars) : could not find function "lazy_dt"
```

I'm using R 3.6.1, 64 bit on Windows, with all packages installed from CRAN and updated to latest versions.

**Comment by hadley** [comment]
You'll need to install the development version of dtplyr.
