### ISSUE TITLE
Filtering based on date variable

### ISSUE THREAD

**Issue by Vidaringa** [tidyverse/dtplyr#95]
Edited with reproducible example.
I have a date variable and I want to filter based on that variable. Works when I manually type in the date I want to use in filter() but when I assign it to a variable I get an error.

``` r
library(tidyverse)
library(reprex)
library(dtplyr)
suppressMessages(library(data.table))
suppressMessages(library(lubridate))


df_test <- tibble(age = sample(25:55, 10),
                  date = today() - years(1:10))

date_filter <- "2015-01-01"

df_test %>% filter(date <= date_filter)
#> # A tibble: 6 x 2
#>     age date      
#>   <int> <date>    
#> 1    43 2014-08-20
#> 2    55 2013-08-20
#> 3    52 2012-08-20
#> 4    49 2011-08-20
#> 5    48 2010-08-20
#> 6    41 2009-08-20


df_lazy <- lazy_dt(df_test)
df_lazy %>% filter(date < "2015-01-01")
#> Source: local data table [?? x 2]
#> Call:   `_DT1`[date < "2015-01-01"]
#> 
#>     age date      
#>   <int> <date>    
#> 1    43 2014-08-20
#> 2    55 2013-08-20
#> 3    52 2012-08-20
#> 4    49 2011-08-20
#> 5    48 2010-08-20
#> 6    41 2009-08-20
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results

df_lazy %>% filter(date < date_filter)
#> Source: local data table [?? x 2]
#> Call:   `_DT1`[date < ..date_filter]
#> Error in .checkTypos(e, names(x)): Object '..date_filter' not found amongst age, date
```

<sup>Created on 2019-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by torema-ed** [comment]
In my experience, data.table do not change string inputs into dates when filtering a date variable.

try `fjoldi_ald_rik_kyn <- df_raw_lazy %>% filter(arma_dags <= ymd(dagsetning_filter))` instead and see if it works?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by Vidaringa** [comment]
> In my experience, data.table do not change string inputs into dates when filtering a date variable.
> 
> try `fjoldi_ald_rik_kyn <- df_raw_lazy %>% filter(arma_dags <= ymd(dagsetning_filter))` instead and see if it works?

It didn't work either. It seems that filtering based on a value that has been assigned to a variable is not supported, see issue #90

**Comment by torema-ed** [comment]
> > In my experience, data.table do not change string inputs into dates when filtering a date variable.
> > try `fjoldi_ald_rik_kyn <- df_raw_lazy %>% filter(arma_dags <= ymd(dagsetning_filter))` instead and see if it works?
> 
> It didn't work either. It seems that filtering based on a value that has been assigned to a variable is not supported, see issue #90

I didn't know dplyr and data.table will convert a date in string to date format for filtering if it is in the ISO 8601 format! Sorry about it.
