### ISSUE TITLE
left_join() acts as an inner_join() -- dropping mismatching rows

### ISSUE THREAD

**Issue by AlanFeder** [tidyverse/dtplyr#96]
Hi, 

I noticed that, while using `dtplyr`, `left_join()` acts as an `inner_join()`, as can be seen in the reprex below.  One would expect the two `left_join`s to have the same number of rows (as one is the standard `dplyr` one, and the other just changes the inputs to `lazy_dt`s), but one actually outputs more rows than the other.

``` r
library(dplyr, warn.conflicts = FALSE)
library(tibble)
library(dtplyr)

a <- tibble(id = 1:39, 
            group = rep(c("a", "b", "c"), 13), 
            y_id = runif(39)) 

b <- tibble(group = c("a", "b"), 
            y_grp = runif(2))

nrow(          left_join(        a,          b,  by = "group"))
#> [1] 39
nrow(as_tibble(left_join(lazy_dt(a), lazy_dt(b), by = "group")))
#> [1] 26
```

<sup>Created on 2019-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by AlanFeder** [comment]
I've been looking a it a bit further, and it does _not_ seem to happen if I don't include the `by` argument explicitly -- it seems to be something about the `step_subset()` function (which is not called by `right_join` or `full_join` or `inner_join`)

``` r
library(dplyr, warn.conflicts = FALSE)
library(tibble)
library(dtplyr)

a <- tibble(id = 1:39, 
            group = rep(c("a", "b", "c"), 13), 
            y_id = runif(39)) 

b <- tibble(group = c("a", "b"), 
            y_grp = runif(2))

nrow(          left_join(        a,          b,  by = "group"))
#> [1] 39
nrow(as_tibble(left_join(lazy_dt(a), lazy_dt(b), by = "group")))
#> [1] 26

nrow(as_tibble(left_join(lazy_dt(a), lazy_dt(b))))
#> Joining, by = "group"
#> [1] 26
```

<sup>Created on 2019-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Oh, hmmm I guess `DT1[DT2]` is equivalent to `right_join(DT1, DT2)`:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)

a <- lazy_dt(data.frame(x = 1:3, y = 1))
b <- lazy_dt(data.frame(x = 2:4, z = 2))

left_join(a, b)
#> Joining, by = "x"
#> Source: local data table [?? x 3]
#> Call:   `_DT1`[`_DT2`, on = .(x)]
#> 
#>       x     y     z
#>   <int> <dbl> <dbl>
#> 1     2     1     2
#> 2     3     1     2
#> 3     4    NA     2
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2019-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
