### ISSUE TITLE
ndjson package breaks with the new version of dtplyr

### ISSUE THREAD

**Issue by lenay12** [tidyverse/dtplyr#98]
---

I attempted to fix the count() issue #33 by following Hadley's suggestion below, unfortunately this had the unexpected result of breaking ndjson package load.

```r
devtools::install_github("hadley/dtplyr")
install.packages(c('data.table','dplyr'))
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
```
When I try to load ndjson library  I get the following error

```r
 library(ndjson) 
```
Error: package or namespace load failed for ‘ndjson’:  object ‘tbl_dt’ is not exported by 'namespace:dtplyr'
--

**Comment by hadley** [comment]
You'll need to file an issue with ndjson
